name: ami_design_pari_na
description: A Flutter Application For Evident BD

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  feather_icons: ^1.0.1
  animated_splash_screen: ^1.1.0
  firebase_core: "0.7.0"
  firebase_auth: "^0.20.1"
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 700
